name: Build a preview version for MarkBook Viewer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout master
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build with Gradle
        run: ./gradlew :markbook-viewer:linkReleaseExecutableMingwX64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: markbook-viewer-${{ github.sha }}
          path: markbook-viewer/build/bin/mingwX64/releaseExecutable/*
